### ISSUE TITLE
Test pipeline detects a fail is missing

### ISSUE THREAD

**Issue by Japoivvb** [poksyy/hospital-project-backend#63]
https://github.com/poksyy/hospital-project-backend/blob/b0566179af713d26c1673ebe1a7f7bd1bfe735ce/.github/workflows/ci-tests.yml#L1

![image](https://github.com/user-attachments/assets/5c5960a7-eeee-4e0c-8f73-662e750b1368)

**Comment by Dynavy** [comment]
Route of the JUnit tests has been changed in order to see if the pipeline detects an error:

![image](https://github.com/user-attachments/assets/786a3b1f-6101-4fbe-ac5b-2df84a9709ce)

We can see that the pipeline build after the changes, detects an error when running the JUnit tests:

![image](https://github.com/user-attachments/assets/65eb0a04-3a0a-4427-8ff3-c7126ad113e0)

Close #63.
